version: '3.8'

services:
  backend:
    build: 
      context: ./backend
    ports:
      - "8000:80"
    volumes:
      - ./backend/mood.db:/var/www/html/mood.db 

  frontend:
    build: 
      context: ./frontend
    ports:
      - "3000:3000"
    environment:
      NEXT_PUBLIC_API_URL: http://backend
    depends_on:
      - backend